export const FETCH_PICSUM_DATA_LIST = 'FETCH_PICSUM_DATA_LIST';
export const FETCH_PICSUM_DATA_LIST_SUCCESS = 'FETCH_PICSUM_DATA_LIST_SUCCESS';
export const FETCH_PICSUM_DATA_LIST_FAILURE = 'FETCH_PICSUM_DATA_LIST_FAILURE';
export const FETCH_TENOR_DATA_LIST = 'FETCH_TENOR_DATA_LIST';
export const FETCH_TENOR_DATA_LIST_SUCCESS = 'FETCH_TENOR_DATA_LIST_SUCCESS';
export const FETCH_TENOR_DATA_LIST_FAILURE = 'FETCH_TENOR_DATA_LIST_FAILURE';
export const CLEAR_DATA = 'CLEAR_DATA';
